grammar.js, src/scanner.c, test/corpus/type_declarations.txt
Previously a multiline variant:
```
type e =
| A
| B
```
required a trailing `;`. Now it is not.
=> Fix multiline variant declarations without terminal semicolon

grammar.js, queries/highlights.scm, test/corpus/expressions.txt, test/highlight/expressions.res
```rescript
let maybeJson = switch Js.Json.parseExn(str) {
| json => Ok(json)
| exception Js.Exn.Error(obj) =>
let message = Js.Exn.message(obj)
Error(#SyntaxError(message->Option.getWithDefault("Syntax error")))
}
```
=> Exception patterns in switch matches

grammar.js, test/corpus/error_scopes.txt
Malformed (typing now) switch expressions no longer cause the rest of the file parse crazy
=> Localize bad switch damage

grammar.js, queries/highlights.scm, test/corpus/error_scopes.txt, test/corpus/expressions.txt, test/corpus/functions.txt, test/corpus/jsx.txt, test/corpus/let_bindings.txt, test/corpus/literals.txt, test/corpus/modules.txt, test/corpus/mutation_statements.txt, test/corpus/type_declarations.txt
- simple `identifier` -> `value_identifier`
- `module_name` -> `module_identifier`
- `nested_*` -> `*_path`
=> Refactor: consistent naming of nodes

grammar.js, test/corpus/type_declarations.txt
Allow `@deriving(abstract)` for example
=> Relax decorator arg constrains

grammar.js, test/corpus/expressions.txt
This used to give errors:
```rescript
switch tuple {
| (Variant1 | Variant2, 42.0) => 10
| _ => 20
}
```
=> Switch of tuples where patterns and literals are mixed

Makefile, grammar.js, test/corpus/jsx.txt, test/corpus/modules.txt
- Allow `module Foo = %extension()`
- Allow plain literals as JSX children: `<Foo> 42 </Foo>`
=> Bring rescript-material-ui to wild test suite

README.md, queries/textobjects.scm
Adds queries for the [`nvim-treesitter/nvim-treesitter-textobjects`](https://github.com/nvim-treesitter/nvim-treesitter-textobjects) plugin, enabling users to navigate, select, and modify ReScript code using text objects. See [nvim-treesitter-textobjects/CONTRIBUTING.md](https://github.com/nvim-treesitter/nvim-treesitter-textobjects/blob/master/CONTRIBUTING.md) for more info.
Notes:
- I had trouble writing a query to select uncurried function parameters so they currently aren't handled properly. Suggestions are welcome 😅
- I had included a sentence in the README mentioning this feature in the previous PR, but I left it out of this one because this repo isn’t directly targeted towards nvim. Do you think it should be included, either here or in the nvim repo?
Previous PR: …
=> feat: add queries for nvim-treesitter-textobjects

grammar.js, queries/highlights.scm, queries/injections.scm, test/corpus/expressions.txt, test/corpus/jsx.txt, test/corpus/let_bindings.txt, test/corpus/type_declarations.txt
Hey there again!
This PR adds:
1. GraphQL injection point
2. Add `injections.scm` for both JS and GraphQL
3. Make `and` and token and add it to keyword `hightlights.scm`
4. Parse let-and statements (`let a = 5 and b = 4`)
5. Parse uncurried labelled function type declarations `type test = (. ~attr: string) => unit`
`tree-sitter test` passes as does `make test_wild`!
Thanks!
=> A few more things

grammar.js, test/corpus/functions.txt, test/corpus/modules.txt, test/corpus/type_declarations.txt
- Allow trailing commas in more cases
- `func(type a, x: 'a)`
- `func(x: @unwrap [#a(#foo), #b(#bar)])`
- `type \"type" = t"`
=> Handle more wild cases

grammar.js, test/corpus/type_declarations.txt
Sometimes we can add decorators during variant declarations, in this case with [reanalyze](https://github.com/rescript-association/reanalyze)
This PR add the support for decorators in this case
=> feat: add support for decorators in variant's type declaration

Makefile, grammar.js, test/corpus/expressions.txt, test/corpus/modules.txt
- Make https://github.com/rescript-association/rescript-lang.org repo a part of `test_wild` suite
- Fix multiple bugs found after that, making the repo 100% legit
Addresses #92
=> Fixes based on rescript-lang.org repo

grammar.js, test/corpus/type_declarations.txt
```res
type person = {@meth "say": (string, string) => unit}
```
```
(type_declaration [0, 0] - [0, 53]
(type_identifier [0, 5] - [0, 11])
(object_type [0, 14] - [0, 53]
(ERROR [0, 15] - [0, 20]
(decorator [0, 15] - [0, 20]
(decorator_identifier [0, 16] - [0, 20])))
(field [0, 21] - [0, 52]
(property_identifier [0, 21] - [0, 26]
(string_fragment [0, 22] - [0, 25]))
(function_type [0, 28] - [0, 52]
(function_type_parameters [0, 28] - [0, 44]
(parameter [0, 29] - [0, 35]
(type_identifier [0, 29] - [0, 35]))
(parameter [0, 37] - [0, 43]
(type_identifier [0, 37] - [0, 43])))
(unit_type [0, 48] - [0, 52]))))))
```
See https://rescript-lang.org/syntax-lookup#meth-decorator
=> support decorator before object property identifier

grammar.js, test/corpus/decorators.txt
Support decorator in `call_arguments`
See https://rescript-lang.org/syntax-lookup#this-decorator
```res
setIncrement(counter, @this (me, amount) => me->setValue(me->getValue + amount))
```
Reanalyze decorators https://github.com/rescript-association/reanalyze/blob/master/EXCEPTION.md
```res
// Silence only the make function
let stringMake2 = (@doesNotRaise String.make)(12, ' ')
// Silence the entire call (including arguments to make)
let stringMake3 = @doesNotRaise String.make(12, ' ')
```
=> better support for decorator

grammar.js, test/corpus/modules.txt
```res
module Error = {
exception ParseError(string)
}
exception ParseError = Error.ParseError
```
```
(module_declaration [0, 0] - [2, 1]
name: (module_identifier [0, 7] - [0, 12])
definition: (block [0, 15] - [2, 1]
(exception_declaration [1, 2] - [1, 30]
(variant_identifier [1, 12] - [1, 22])
(variant_parameters [1, 22] - [1, 30]
(type_identifier [1, 23] - [1, 29])))))
(exception_declaration [4, 0] - [4, 39]
(ERROR [4, 10] - [4, 29]
(variant_identifier [4, 10] - [4, 20]))
(variant_identifier [4, 29] - [4, 39])))
```
https://rescript-lang.org/try?code=LYewJgrgNgpgBAUQE5JEuBeOBvAUHOGADwGMYAHAFwEsQA7OABQEMkBnGZVJACjcqTU6AcwCUuAL65cxMlVoMW7TijSZEqpADolHLmlxA
=> allow exception assignment

grammar.js, queries/highlights.scm, test/corpus/expressions.txt
> Rescript versions < 9.0 had a when clause, not an if clause.  Rescript 9.0 changed when to if.  (when may still work, but is deprecated.)
https://rescript-lang.org/docs/manual/latest/pattern-matching-destructuring#if-clause
https://rescript-lang.org/try?code=DYUwLgBAZg9jEF4IEYAMyBQpIENEQGcB3ASzAGMALaOCAbwwB8IAPCEqViAPggBYATBABkwrgB4IATimJeAIhbymXIpRAA7LrzSo5EeeoBOIZcwD6++QGYBygL4YMQA
=> support when clause

grammar.js, test/corpus/type_declarations.txt
```res
type basicBlueTone<'a> = [> #Blue | #DeepBlue | #LightBlue ] as 'a
```
```
(ERROR [0, 0] - [0, 66]
(type_identifier [0, 5] - [0, 18])
(type_parameters [0, 18] - [0, 22]
(type_identifier [0, 19] - [0, 21]))
(function_type_parameters [0, 25] - [0, 60]
(polyvar_type [0, 25] - [0, 60]
(polyvar_declaration [0, 28] - [0, 33]
(polyvar_identifier [0, 28] - [0, 33]))
(polyvar_declaration [0, 36] - [0, 45]
(polyvar_identifier [0, 36] - [0, 45]))
(polyvar_declaration [0, 48] - [0, 58]
(polyvar_identifier [0, 48] - [0, 58]))))
(ERROR [0, 65] - [0, 66])))
```
https://rescript-lang.org/docs/manual/latest/polymorphic-variant#lower-bound-
https://rescript-lang.org/try?code=C4TwDgpgBARghgZwJYGMBCAbArhAKgewDsIAeAcjgD4oBeKAbWoGJMcoAfKJgEQgjFbROTADJIA5gAtgggLpREUCgChQkKCnwZ …
=> support `as` in polyvar_type

grammar.js, test/corpus/decorators.txt, test/corpus/expressions.txt, test/corpus/functions.txt, test/corpus/let_bindings.txt
```res
let f = ({name, _} as foo: T.t) => {}
```
```
(source_file [0, 0] - [4, 0]
(let_binding [0, 0] - [0, 37]
(value_identifier [0, 4] - [0, 5])
(function [0, 8] - [0, 37]
parameters: (formal_parameters [0, 8] - [0, 25]
(record_pattern [0, 9] - [0, 18]
(value_identifier [0, 10] - [0, 14])
(value_identifier [0, 16] - [0, 17]))
(as_aliasing [0, 19] - [0, 25]
(value_identifier [0, 22] - [0, 25])))
return_type: (type_annotation [0, 25] - [0, 30]
(type_identifier_path [0, 27] - [0, 30]
(module_identifier [0, 27] - [0, 28])
(type_identifier [0, 29] - [0, 30])))
(ERROR [0, 30] - [0, 31])
body: (block [0, 35] - [0, 37]))))
```
https://rescript-lang.org/try?code=LYewJgrgNgpgBAFTgXjgbwFBzgFwJ4AO8OK6AdgIbAwBccAzjgE4CWZA5gDRwXu1xscAXwwiM+InABmIEKTSVqdRqw7de-FW3ZjYJKaQAUaDUJ704IVuzYUodBADocAShQA+dFjg …
=> as_aliasing, add type annotation

grammar.js, test/corpus/type_declarations.txt
```res
type point2d = {
"x": float,
"y": float,
}
type point3d = {
...point2d,
"z": float,
}
```
```
(source_file [0, 0] - [8, 0]
(type_declaration [0, 0] - [3, 1]
(type_identifier [0, 5] - [0, 12])
(object_type [0, 15] - [3, 1]
(field [1, 2] - [1, 12]
(property_identifier [1, 2] - [1, 5]
(string_fragment [1, 3] - [1, 4]))
(type_identifier [1, 7] - [1, 12]))
(field [2, 2] - [2, 12]
(property_identifier [2, 2] - [2, 5]
(string_fragment [2, 3] - [2, 4]))
(type_identifier [2, 7] - [2, 12]))))
(type_declaration [4, 0] - [7, 1]
(type_identifier [4, 5] - [4, 12])
(object_type [4, 15] - [7, 1]
(ERROR [5, 4] - [5, 13]
(ERROR [5, 5] - [5, 7])
(ERROR [5, 9] - [5, 10])
(number [5, 10] - [5, 11])
(ERROR [5, 11] - [5, 12]))
(field [6, 2] - [6, 12]
(property_identifier [6, 2] - [6, 5]
(string_fragment …
```
=> support spread object

grammar.js, test/corpus/literals.txt
This type is not documented. I found it in dakrlang codebase https://github.com/darklang/dark/blob/1205eb27b1eadd94dd3378e3abb92663035cc245/client/src/app/IntegrationTest.res#L249
https://rescript-lang.org/try?code=DYUwLgBAlgdmBsAWCBeCBtAUBCBGAMgDTZ4D6ATKQMxEkC0BxODF1tOADAEa6kf99+7CBwAeAM0lTJwjgHtc5KolnC6HWYn4biAXUxA
=> support int64

grammar.js, test/corpus/expressions.txt
More cases with parentheses in `switch_match`. Now inside variant.
```res
switch n {
| (1 | 2) => 1
| (n if n > 10 | n if n < 42) | 50 | (n if n > 100) => n
| Some((This | That) | Unknow) => 0
}
```
```
(expression_statement [0, 0] - [4, 1]
(switch_expression [0, 0] - [4, 1]
(value_identifier [0, 7] - [0, 8])
(switch_match [1, 0] - [1, 14]
(number [1, 3] - [1, 4])
(number [1, 7] - [1, 8])
(expression_statement [1, 13] - [1, 14]
(number [1, 13] - [1, 14])))
(switch_match [2, 0] - [2, 56]
(value_identifier [2, 3] - [2, 4])
(switch_pattern_condition [2, 5] - [2, 14]
(binary_expression [2, 8] - [2, 14]
left: (value_identifier [2, 8] - [2, 9])
right: (number [2, 12] - [2, 14])))
(value_identifier [2, 17] - [2, 18])
(switch_pattern_condition [2, 19] - [2, 28] …
```
=> Fix variant pattern

grammar.js, queries/highlights.scm, test/corpus/expressions.txt, test/highlight/expressions.res
```res
switch foo {
| list{} => None
| list{1, 2, ...list{b, ..._} as rest} => Some(rest)
}
```
```
(source_file [0, 0] - [4, 0]
(expression_statement [0, 0] - [3, 1]
(switch_expression [0, 0] - [3, 1]
(value_identifier [0, 7] - [0, 10])
(switch_match [1, 0] - [1, 16]
(list_pattern [1, 2] - [1, 8])
(expression_statement [1, 12] - [1, 16]
(variant [1, 12] - [1, 16]
(variant_identifier [1, 12] - [1, 16]))))
(switch_match [2, 0] - [2, 52]
(list_pattern [2, 2] - [2, 29]
(number [2, 7] - [2, 8])
(number [2, 10] - [2, 11])
(spread_pattern [2, 13] - [2, 20]
(value_identifier [2, 16] - [2, 20]))
(ERROR [2, 20] - [2, 22]
(ERROR [2, 21] - [2, 22]))
(spread_pattern [2, 24] - [2, 28]
(value_identifier [2, 27] - [2, 28])))
(as_aliasing [2, 30] - [2, 37]
(value_identifier [2, 33] - [2, 37]))
(ERROR [2, …
```
=> support nested list_pattern with spread

grammar.js, test/corpus/modules.txt, test/highlight/modules.res
Currently the following code is parsed as a `call_expression`. Actually this is destructuring modules [https://rescript-lang.org/docs/manual/latest/module#destructuring-modules](https://rescript-lang.org/docs/manual/latest/module#destructuring-modules)
```res
let {baz, _} = module(User.Inner)
```
Before:
```
(let_binding [0, 0] - [0, 33]
(record_pattern [0, 4] - [0, 12]
(value_identifier [0, 5] - [0, 8])
(value_identifier [0, 10] - [0, 11]))
(call_expression [0, 15] - [0, 33]
function: (value_identifier [0, 15] - [0, 21])
arguments: (arguments [0, 21] - [0, 33]
(variant [0, 22] - [0, 32]
(nested_variant_identifier [0, 22] - [0, 32]
(module_identifier [0, 22] - [0, 26])
(variant_identifier [0, 27] - [0, 32])))))))
```
After:
```
let_binding [0, 0] - [0, 33] …
```
=> support destructuring modules

grammar.js, test/corpus/expressions.txt, test/corpus/functions.txt
```res
let polymorphicComponent = (~p as (x, _)) => React.string(x.name)
```
```
(let_binding [0, 0] - [0, 65]
(value_identifier [0, 4] - [0, 24])
(function [0, 27] - [0, 65]
parameters: (formal_parameters [0, 27] - [0, 41]
(ERROR [0, 28] - [0, 33]
(value_identifier [0, 29] - [0, 30]))
(parameter [0, 34] - [0, 40]
(tuple_pattern [0, 34] - [0, 40]
(tuple_item_pattern [0, 35] - [0, 36]
(value_identifier [0, 35] - [0, 36]))
(tuple_item_pattern [0, 38] - [0, 39]
(value_identifier [0, 38] - [0, 39])))))
body: (call_expression [0, 45] - [0, 65]
function: (value_identifier_path [0, 45] - [0, 57]
(module_identifier [0, 45] - [0, 50])
(value_identifier [0, 51] - [0, 57]))
arguments: (arguments [0, 57] - [0, 65]
(member_expression [0, 58] - [0, 64]
record: …
```
=> support pattern in as_aliasing rule

grammar.js, test/corpus/decorators.txt, test/corpus/let_bindings.txt, test/corpus/type_declarations.txt
=> Fix decorators before `and` in `let` and `type` statements

grammar.js, test/corpus/decorators.txt, test/corpus/expressions.txt, test/corpus/functions.txt, test/corpus/jsx.txt, test/corpus/let_bindings.txt, test/corpus/modules.txt, test/corpus/type_declarations.txt
**Add support for `module_pack` in parameters**
https://github.com/rescriptbr/rescript-urql/blob/main/src/Client.res#L248-L251
**Support `module_pack` after `as`**
https://github.com/rescriptbr/rescript-urql/blob/main/src/Client.res#L327
**Other changes**
1. Removed `module_pack_type`
2. A new rule to match this cases `repeat1(seq($.module_identifier, '.'))`
3. Two new rules `constrain_module` and `constrain_type`
=> Better support for modules

grammar.js, test/corpus/decorators.txt, test/corpus/expressions.txt, test/corpus/functions.txt, test/corpus/jsx.txt, test/corpus/let_bindings.txt, test/corpus/modules.txt, test/corpus/type_declarations.txt
- Remove a bunch of conflicts
- Generalize and relax module path-based access for many rules
- Remove superfluous `module_nested_path` nesting
=> Simplify grammar

grammar.js, queries/highlights.scm, test/corpus/expressions.txt, test/corpus/let_bindings.txt
Close #149
[Playground](https://rescript-lang.org/try?code=DYUwLgBMCGBeCeBGCBeKd4QN4CgIQCIAJEYYAewBp0ECBaAPgCkBnAOgoHM8JEcBfHDlCQYCAEyoamAMxDWHcp3EAKMUmrrxASiEjpEAB5T1veey4rDuoA)
=> support lazy

grammar.js, queries/highlights.scm, test/corpus/functions.txt, test/corpus/let_bindings.txt, test/highlight/functions.res
Part of ReScript v10.1 features:
- `async` could be a valid identifier (same for JS). eg `let f = (async) => async + 1`, `let async = 1`
```res
let f = (async) => async + 1
```
It is currently an error:
```
(let_binding [0, 0] - [0, 28]
(value_identifier [0, 4] - [0, 5])
(function [0, 8] - [0, 28]
parameters: (formal_parameters [0, 8] - [0, 15]
(ERROR [0, 9] - [0, 14]))
(ERROR [0, 19] - [0, 24])
body: (unary_expression [0, 25] - [0, 28]
argument: (number [0, 27] - [0, 28])))))
```
=> fix: allow `async` as valid identifier

src/scanner.c
=> fix: scan inline white space

grammar.js, test/corpus/decorators.txt
See [reanalyze exampes](https://github.com/rescript-association/reanalyze/blob/388149046bf077d17639f50d4c7aea2bdd28b8b5/examples/deadcode/src/noalloc/Chess.res#L19-L20)
```res
@local
call()
```
```
(source_file [0, 0] - [2, 0]
(ERROR [0, 0] - [1, 6]
(decorator [0, 0] - [1, 6]
(decorator_identifier [0, 1] - [0, 6])
(ERROR [1, 0] - [1, 4]
(ERROR [1, 0] - [1, 4]))
(decorator_arguments [1, 4] - [1, 6]))))
```
=> feat: support decorated expressions

grammar.js, test/corpus/type_declarations.txt
Addresses #141 
Empty record _literals_ are not treated as records at all, but are (still) interpreted as `block`’s. Although it is incorrect semantically, I think it is OK for the purposes of `tree-sitter-rescript`.
@aspeddro, what do you think?
=> Support empty record {} type declaration

Makefile, grammar.js, test/corpus/let_bindings.txt
=> Support reanalyze examples

grammar.js, test/corpus/decorators.txt
Related: #171 
```res
module MainParser = {
type rec tree = {
rootNode: syntaxNode,
copy: unit => tree,
getLanguage: unit => language,
}
and syntaxNode = {
id: int,
text: string,
@as("type") type_: string,
tree: tree,
}
and language = {load: (. string) => Js.Promise.t<language>}
and point = {row: int, column: int}
and input =
String(string) | Input({startIndex: int, startPoint: point, endIndex: int})
and t = {
init: (. unit) => Js.Promise.t<unit>,
setLanguage: (. language) => unit,
parse: (. string) => tree,
language: language,
}
@send external toString: syntaxNode => string = "toString"
let parse = (t, input) =>
switch input {
| String(s) => t.parse(. s)
| _ => t.parse(. "Js.log")
}
}
```
```
yarn run v1.22.19
$ /home/pedro/Desktop/projects/tree-sitter-rescript/node_modules/.bin/tree-sitt …
```
=> fix: consecutive `and` bindings for type and module

grammar.js, test/corpus/type_declarations.txt
Here an [example](https://github.com/TheSpyder/rescript-nodejs/blob/7321edeff2e836dae5886e3a1124b1227bd8765d/src/Http2.res#L17).
```res
type subtype<'w, 'ty> = Stream.subtype<[> kind<'w, 'r>] as 'ty>
```
```
(ERROR [0, 0] - [1, 0]
(type_identifier [0, 5] - [0, 12])
(type_parameters [0, 12] - [0, 21]
(type_identifier [0, 13] - [0, 15])
(type_identifier [0, 17] - [0, 20]))
(generic_type [0, 24] - [0, 54]
(type_identifier_path [0, 24] - [0, 38]
(module_identifier [0, 24] - [0, 30])
(type_identifier [0, 31] - [0, 38]))
(ERROR [0, 38] - [0, 46]
(polyvar_declaration [0, 42] - [0, 46]
(type_identifier [0, 42] - [0, 46])))
(type_arguments [0, 46] - [0, 54]
(type_identifier [0, 47] - [0, 49])
(type_identifier [0, 51] - [0, 53])))
(ERROR [0, 60] - [0, 62]))
```
=> feat: relax rule to polyvar_declaration

grammar.js, test/corpus/functions.txt, test/corpus/type_declarations.txt
=> support polymorphic type and locally abstract type

grammar.js, test/corpus/modules.txt, test/corpus/type_declarations.txt
Trailing and infix ticks are allowed in the following identifiers:
- Modules (fixes #180)
- Variants
- Polyvars
- Types
=> Allow ticks in more identifiers

grammar.js, test/corpus/type_declarations.txt
Example from [rescript-nodejs](https://github.com/TheSpyder/rescript-nodejs/blob/f20b20744cf66440b4f4cc2983838ebaff8995bd/src/Fs.res#L430)
```res
@send
external onReady: (
subtype<'w, [> kind<'w>]> as 'stream,
@as("ready") _,
@uncurry (unit => unit),
) => 'stream = "on"
```
```
yarn run v1.22.19
$ /home/pedro/Desktop/projects/tree-sitter-rescript/node_modules/.bin/tree-sitter parse ../../test-filetypes/rescript_print.res
(source_file [0, 0] - [6, 0]
(decorated [0, 0] - [5, 19]
(decorator [0, 0] - [0, 5]
(decorator_identifier [0, 1] - [0, 5]))
(external_declaration [1, 0] - [5, 19]
(value_identifier [1, 9] - [1, 16])
(type_annotation [1, 16] - [5, 12]
(function_type [1, 18] - [5, 12]
(function_type_parameters [1, 18] - [5, 1]
(parameter [2, 2] - [2, 27]
(generic_type [2, 2] - [2, 27] …
```
=> fix: support aliasing type for generic-type

grammar.js, test/corpus/type_declarations.txt
Example from [rescript-nodejs](https://github.com/TheSpyder/rescript-nodejs/blob/46f8e255d0375a6db9f361200189dd254c9b3953/src/Net.res#L306)
```res
type subtype<'ty> constraint 'ty = [> kind]
```
```
yarn run v1.22.19
$ /home/pedro/Desktop/projects/tree-sitter-rescript/node_modules/.bin/tree-sitter parse ../../test-filetypes/rescript_print.res
(ERROR [0, 0] - [1, 0]
(type_declaration [0, 0] - [0, 17]
(type_identifier [0, 5] - [0, 12])
(type_parameters [0, 12] - [0, 17]
(type_identifier [0, 13] - [0, 16])))))
../../test-filetypes/rescript_print.res	0 ms	(ERROR [0, 0] - [1, 0])
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
=> fix: type constraint

Makefile, grammar.js, test/corpus/expressions.txt, test/corpus/let_bindings.txt, test/corpus/type_declarations.txt
1. Decorator before `polyvar_type`:
```res
type barStyle = @string [
| #default
| @as("light-content") #lightContent
| @as("dark-content") #darkContent
]
```
```
yarn run v1.22.19
$ /home/pedro/Desktop/projects/tree-sitter-rescript/node_modules/.bin/tree-sitter parse ../../test-filetypes/rescript_print.res
(type_declaration [0, 0] - [4, 1]
(type_identifier [0, 5] - [0, 13])
(ERROR [0, 16] - [0, 23]
(decorator [0, 16] - [0, 23]
(decorator_identifier [0, 17] - [0, 23])))
(polyvar_type [0, 24] - [4, 1]
(polyvar_declaration [1, 4] - [1, 12]
(polyvar_identifier [1, 4] - [1, 12]))
(polyvar_declaration [2, 4] - [2, 38]
(decorator [2, 4] - [2, 24]
(decorator_identifier [2, 5] - [2, 7])
(decorator_arguments [2, 7] - [2, 24]
(string [2, 8] - [2, 23]
(string_fragment [2, …
```
=> Support decorators (take 3)

grammar.js, test/corpus/literals.txt
Any prefix is valid by syntax, but is removed on compilation.
See [playground](https://rescript-lang.org/try?code=DYUwLgBAhhC8ECsDOB7AdgAwN4DMUCcBbKMALgCIBXMHADnIBoIBLNAY2EoBMQBlMSjhykIOKMCQgAvhgBQoSACM40NAE8wAC1YYAEiGDAUchRDYqAOuS3Mk5PQaMYgA)
=> fix: relax template string prefix

grammar.js, test/corpus/comments.txt, test/corpus/expressions.txt
This PR is a proposal to improve AST to `switch_match`
Currently, the exposed nodes in the tree are few. By exposing more nodes I can get better features like a better indentation.
Example:
```res
switch n {
| 1 | 2 => Ok
| _ => Failed
}
```
Before:
```
(expression_statement [0, 0] - [3, 1]
(switch_expression [0, 0] - [3, 1]
(value_identifier [0, 7] - [0, 8])
(switch_match [1, 0] - [1, 13]
(number [1, 2] - [1, 3])
(number [1, 6] - [1, 7])
(expression_statement [1, 11] - [1, 13]
(variant [1, 11] - [1, 13]
(variant_identifier [1, 11] - [1, 13]))))
(switch_match [2, 0] - [2, 13]
(value_identifier [2, 2] - [2, 3])
(expression_statement [2, 7] - [2, 13]
(variant [2, 7] - [2, 13]
(variant_identifier [2, 7] - [2, 13])))))))
```
After:
``` …
```
=> improve switch match

grammar.js, queries/highlights.scm, test/corpus/let_bindings.txt
`unpack` can be an identifier.
[Playground example](https://rescript-lang.org/try?version=v10.1.2&code=DYUwLgBArgdgDgQwMYGsIF4IEYBQOC2A9gCZSgRgCecIEAGhhAN44QXW1h5uiQLHEAXBAAUASxhgANBAlgAlBgB8syTgC+eKjQgAzRkVKgRdeXl4QEBkmRAjWzB222cnEC-2KMRCGQCNFdBUrAGoIPwd1YTocMwIbcgAhRlhEVB8zIA)
=> allow `unpack` as a valid identifier

grammar.js, test/corpus/expressions.txt
```rescript
try for i in 0 to 200 {
Js.log(i)
} catch {
| Not_found => ()
}
```
[Playground](https://rescript-lang.org/try?version=v10.1.2&code=C4JwngBAZg9iEEtEDsIAYLBhATGjA3gFAQQBSAzgHQA2MA5gBQICURAvhAMYCGwXACwjEAPhAByMYAH1YAV2QATCAF4AfBEZt2RIA)
```
(expression_statement [0, 0] - [4, 1]
(try_expression [0, 0] - [4, 1]
(ERROR [0, 4] - [0, 21]
(value_identifier [0, 4] - [0, 7])
(ERROR [0, 8] - [0, 9])
(number [0, 13] - [0, 14])
(number [0, 18] - [0, 21]))
(block [0, 22] - [2, 1]
(expression_statement [1, 2] - [1, 11]
(call_expression [1, 2] - [1, 11]
function: (value_identifier_path [1, 2] - [1, 8]
(module_identifier [1, 2] - [1, 4])
(value_identifier [1, 5] - [1, 8]))
arguments: (arguments [1, 8] - [1, 11]
(value_identifier [1, 9] - [1, 10])))))
(switch_match …
```
=> try_expression: allow `expression`

grammar.js, test/corpus/modules.txt
```rescript
include (
{
let a = Js.log("Hello")
}: {
let a: unit
}
)
``` 
```
(source_file [0, 0] - [7, 0]
(ERROR [0, 0] - [0, 9])
(ERROR [1, 2] - [3, 4]
(block [1, 2] - [3, 3]
(let_declaration [2, 4] - [2, 27]
(let_binding [2, 8] - [2, 27]
pattern: (value_identifier [2, 8] - [2, 9])
body: (call_expression [2, 12] - [2, 27]
function: (value_identifier_path [2, 12] - [2, 18]
(module_identifier [2, 12] - [2, 14])
(value_identifier [2, 15] - [2, 18]))
arguments: (arguments [2, 18] - [2, 27]
(string [2, 19] - [2, 26]
(string_fragment [2, 20] - [2, 25]))))))))
(expression_statement [3, 5] - [5, 3]
(block [3, 5] - [5, 3]
(let_declaration [4, 4] - [4, 15]
(let_binding [4, 8] - [4, 15]
pattern: (value_identifier [4, 8] - [4, 9])
(type_annotation [4, 9] - [4, 15]
(unit_type [4, 11] - [4, 15])))))) …
```
=> Fix include_statement

grammar.js, queries/highlights.scm, src/scanner.c, test/corpus/decorators.txt, test/corpus/let_bindings.txt, test/corpus/literals.txt, test/corpus/modules.txt, test/corpus/type_declarations.txt, test/highlight/decorators.res
Move inline decorator to scanner.
Inline decorator is decorator without arguments.
```rescript
@@decorator
@decorator
``` 
Decorators with arguments can be specified in `grammar.js`. This was a limitation because TreeSitter could not determine the end of the rule. 
Decorators can now be treated as a comment, can appear anywhere.
This PR also removes some conflicts that were introduced due to decorators. We can also remove some tests with decorators.
=> Move inline decorator to scanner

test/corpus/comments.txt, test/corpus/decorators.txt, test/corpus/expressions.txt, test/corpus/jsx.txt, test/corpus/let_bindings.txt, test/corpus/literals.txt, test/corpus/modules.txt, test/corpus/type_declarations.txt
Remove `decorator` nodes 20abe87c00a844fb5b81300bf3b76a75b2fe8049 and
format tests with `tree-sitter test --update` f41ba3ece49b1e48b9cf6dc589ad1d06ec5ab687
=> Cleanup decorator tests

src/scanner.c
I got the following error when compile to wasm on CI:
```
src/scanner.c:154:9: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
const in_string = state->in_quotes || state->in_backticks;
~~~~~ ^
int
1 error generated.
emcc: error: '/emsdk/upstream/bin/clang -target wasm32-unknown-emscripten -fignore-exceptions -fPIC -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -DEMSCRIPTEN -Werror=implicit-function-declaration -I/emsdk/upstream/emscripten/cache/sysroot/include/SDL --sysroot=/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -Os -fno-exceptions -Isrc src/scanner.c -c -o /tmp/emscripten_temp_kz9rxsh8/scanner_0.o' failed (returned …
```
=> Scanner: add type specifier missing

src/scanner.c
Example: `"// "` no newline before EOF.
=> Fix infinite loop in scanner.

grammar.js, src/grammar.json, src/node-types.json, test/corpus/modules.txt
=> handle module paths in member_expression

grammar.js, src/grammar.json
This doesn't change the grammar at all, just cleans it up a bit per the error message given when running `tree-sitter g` on the current build (with HEAD CLI version).
See https://github.com/nvim-treesitter/nvim-treesitter/pull/6671#issuecomment-2250047437
=> fix: remove redundant `seq` call
