rescript-lang/tree-sitter-rescript

grammar.js
test/corpus/type_declarations.txt

```
type t = {
@as("type")
type_: string,
}
```

Decorated record fields

---

grammar.js
queries/highlights.scm
test/corpus/jsx.txt
test/corpus/let_bindings.txt
test/corpus/literals.txt
test/corpus/type_declarations.txt
test/highlight/literals.res

```rescript
#Bar(7)
#"baz"
#\"qux"
#77
```

Non-trivial polyvar literals

---

grammar.js
queries/highlights.scm
test/corpus/literals.txt
test/highlight/literals.res

Character literals

---

queries/highlights.scm
test/highlight/modules.res

Highlight keywords only, not the contents

Fix include/open highlight

---

grammar.js
test/corpus/modules.txt

```rescript
module rec BYOBReader: {
include Reader
} = BYOBReader
```

Recursive modules

---

grammar.js
queries/highlights.scm
test/corpus/expressions.txt
test/corpus/modules.txt
test/highlight/expressions.res

Exceptions

---

grammar.js
test/corpus/type_declarations.txt

fix(polyvar): when using polyvar's sum in type declarations

---

grammar.js
test/corpus/type_declarations.txt

This PR depends on #45 
fix #46

fix(polyvar): @as decorator on type declaration 

---

grammar.js
queries/highlights.scm
test/corpus/expressions.txt
test/highlight/expressions.res

Match polyvar type in switch statement

---

grammar.js
test/corpus/expressions.txt

Statements in extension points

---

grammar.js
test/corpus/expressions.txt

Quick’n’dirty solution, not entirely correct, nevertheless fixes the second case of #49

Patterns in records

---

grammar.js
queries/highlights.scm
test/corpus/error_scopes.txt
test/corpus/expressions.txt
test/corpus/functions.txt
test/corpus/let_bindings.txt

Unify patterns

---

grammar.js
test/corpus/jsx.txt

Support arbitrary blocks nested inside JSX

---

.gitignore
grammar.js
test/corpus/expressions.txt
test/corpus/type_declarations.txt

Hey there!
This PR adds some enhancements and fixes a few bugs I found while using this tree sitter in another project! I've updated `grammar.js`, added tests, and have made sure that `make test_wild` runs with no issues. The enhancements/bugs are:
1. Wrap raw JS in it's own node for JS tree sitter injection
2. Parsing mutually recursive type declarations (https://github.com/nkrkv/tree-sitter-rescript/issues/56)
2. Parsing a list of statements in a case branch
3. Having multiple statements in a `%%private(...)`
Sorry theses aren't broken up into multiple PRs. These fixes were just based on use in my projects and I figured others may benefit from them too.
Thanks for the great project!

Enhancements & fix a few bugs

---

grammar.js
src/scanner.c

Refactor: make grammar simpler

---

grammar.js
test/corpus/expressions.txt

feat: add support for `as_aliasing` in polyvar pattern

---

queries/locals.scm

from https://github.com/nkrkv/nvim-treesitter-rescript/pull/7

add basic support locals

---

grammar.js
queries/highlights.scm
test/corpus/expressions.txt

Loop expressions support

---

grammar.js
test/corpus/expressions.txt

fix: destructured polyvar type in pattern matching works in tuples

---

queries/highlights.scm
test/highlight/expressions.res
test/highlight/type_declarations.res

Fix lost object property highlighting

---

src/scanner.c
test/corpus/comments.txt

Fix multiline comments with asterisks and slashes mixed closely

---

grammar.js
test/corpus/let_bindings.txt

Fix module paths in record desctructuring

---

grammar.js
test/corpus/expressions.txt

Fix %raw payload with string prefixed by j

---

grammar.js
test/corpus/expressions.txt

Allow non-block expression in try expression body

---

grammar.js
test/corpus/expressions.txt

Allow parenthesized expression as pipe target

---

grammar.js
test/corpus/expressions.txt

Support block expression on the right-hand side of pipe expression

---

grammar.js
test/corpus/expressions.txt

More support for expression type annotations

---

grammar.js
test/corpus/expressions.txt
test/corpus/type_declarations.txt

Optional record fields

---

grammar.js
queries/highlights.scm
test/corpus/expressions.txt
test/corpus/functions.txt

They are upcoming in ReScript 10.1 or something, but looks like they would be there anyway.
Support in advance.

Suport for async/await

---

grammar.js
test/corpus/let_bindings.txt

fix tuple destructuring unit

---

grammar.js
queries/highlights.scm
test/corpus/expressions.txt

remove raise expression

---

grammar.js
test/corpus/expressions.txt

Allow parens in switch patterns

---

grammar.js
queries/highlights.scm
test/corpus/expressions.txt

Support for switch range patterns

---

grammar.js
test/corpus/let_bindings.txt

add list and array pattern

---

grammar.js
queries/highlights.scm
test/corpus/modules.txt
test/highlight/modules.res

better support include_statement

---

grammar.js
queries/highlights.scm
test/corpus/let_bindings.txt
test/corpus/modules.txt
test/corpus/type_declarations.txt
test/highlight/modules.res
test/highlight/type_declarations.res

Documentation: https://github.com/rescript-association/rescript-lang.org/issues/155
Example: https://alexfedoseev.com/blog/post/cool-things-you-can-do-with-first-class-modules-in-rescript-react and https://forum.rescript-lang.org/t/syntax-for-first-class-modules/980
Reanalyze examples:
- https://github.com/rescript-association/reanalyze/blob/master/examples/deadcode/src/FirstClassModules.res
- https://github.com/rescript-association/reanalyze/blob/master/examples/deadcode/src/TestFirstClassModules.res

support first class modules

---

grammar.js
test/corpus/expressions.txt

```res
let f = () => assert false
```
```
(let_binding [0, 0] - [0, 26]
(value_identifier [0, 4] - [0, 5])
(function [0, 8] - [0, 26]
parameters: (formal_parameters [0, 8] - [0, 10])
(ERROR [0, 14] - [0, 20]
(value_identifier [0, 14] - [0, 20]))
body: (false [0, 21] - [0, 26]))))
```
https://rescript-lang.org/try?code=DYUwLgBAZhC8EAoCUcB8ECGBnLIBOkUGwuAUEA

move `assert` to expression

---

grammar.js
test/corpus/type_declarations.txt

Related: https://github.com/rescript-association/rescript-lang.org/issues/149 and https://forum.rescript-lang.org/t/is-the-more-obscure-language-syntax-documented-somewhere/1663/2

support variance annotation

---

queries/highlights.scm

Regression possibly introduced by #116

Fix non-labeled parameter in parens highlight

---

grammar.js
test/corpus/type_declarations.txt

fix: allow unit `()` in type_arguments

---

grammar.js
test/corpus/literals.txt

support int32

---

grammar.js
test/corpus/modules.txt

Support `and` rec module

---

grammar.js
test/corpus/type_declarations.txt

support as-aliasing-type

---

grammar.js
test/corpus/decorators.txt

support decorator with type

---

grammar.js
test/corpus/jsx.txt

support spread props

---

grammar.js
test/corpus/expressions.txt

fix: pipe expression rhs

---

test/corpus/expressions.txt

Missing test update after #183

Fix pipe test

---

queries/highlights.scm
test/highlight/functions.res

Highlight destructuring parameters in function declarations

---

grammar.js
test/corpus/modules.txt

support unpack with constrain type

---

grammar.js
queries/textobjects.scm
test/corpus/decorators.txt
test/corpus/expressions.txt
test/corpus/functions.txt
test/corpus/jsx.txt
test/corpus/let_bindings.txt
test/corpus/modules.txt
test/corpus/type_declarations.txt

More structured ast

---

test/corpus/modules.txt

Broken due to not rebasing #199 onto #197

Fix modules test

---

grammar.js
queries/highlights.scm
src/scanner.c
test/highlight/expressions.res

refactor: move list identifier to scanner

---

grammar.js
test/corpus/literals.txt

fix: template string empty char

---

grammar.js
test/corpus/type_declarations.txt

Better support for aliased type

---

grammar.js
test/corpus/literals.txt

Number: hex literal and decimal

---

grammar.js
test/corpus/functions.txt

Fix pattern with type annotation

---

grammar.js
test/corpus/expressions.txt

Variant: add `?` prefix

---

grammar.js
test/corpus/modules.txt

Fix functor

---

grammar.js
test/corpus/expressions.txt

Fix lazy pattern
